name: PR check

on:
  pull_request:
    branches:
      - "release-*"

jobs:
  test-default-branch:
    name: base branch is a default branch
    runs-on: ubuntu-latest
    steps:
    - name: fail if base branch is not default branch
      if: ${{ github.event.pull_request.base.ref != github.event.repository.default_branch }}
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
            core.setFailed("Base branch of the PR - ${{ github.event.pull_request.base.ref }} is not a default branch. Please reopen your PR to ${{ github.event.repository.default_branch }}")
